datasets:
- name: gaia
  total_examples: 165
- name: simpleQA
  total_examples: 4326
- name: hle
  total_examples: 2500
evaluation_runs:
  gaia:
    evaluation_1:
      branch: main
      commit: 4778a5a291edf56667be91dee1612249525006f9
      eval_id: 8d366e8f-8fbb-4686-adb9-03eb5da54fdb
      examples_evaluated: 5
      name: evaluation_1
    evaluation_2:
      branch: main
      commit: 4778a5a291edf56667be91dee1612249525006f9
      eval_id: 78491430-4934-40fd-ac1e-4583aa13436c
      examples_evaluated: 165
      name: evaluation_2
    evaluation_trail_1:
      branch: main
      commit: 595b0421c54d4008f92b3c6e693e74e1f283f999
      eval_id: 7ff8b888-7bbe-4fa7-b53d-641d860803eb
      examples_evaluated: 2
      name: evaluation_trail_1
  hle: {}
  simpleQA: {}
total_evaluation_runs: 3
