datasets:
- name: gaia
  total_examples: 165
- name: simpleQA
  total_examples: 4326
- name: hle
  total_examples: 2500
evaluation_runs:
  gaia:
    evaluation_trail_1:
      branch: main
      commit: 595b0421c54d4008f92b3c6e693e74e1f283f999
      eval_id: 7ff8b888-7bbe-4fa7-b53d-641d860803eb
      examples_evaluated: 2
      name: evaluation_trail_1
  hle: {}
  simpleQA: {}
total_evaluation_runs: 1
